# --- GENERAL SETTINGS ---
general.import = ["/home/antonio/.config/alacritty/themes/dracula.toml"] # Paths to other configuration files
terminal.shell = { program = "/bin/zsh", args = ["--login"] }
working_directory = "None" # Or a specific path like "/home/user"
general.live_config_reload = true


# --- WINDOW ---
[window]
dimensions = { columns = 80, lines = 24 }
position = "None" # e.g., { x = 0, y = 0 }
#padding = { x = 5, y = 5 }
#dynamic_padding = false
#decorations = "Full" # Full, None, Transparent, Buttonless
opacity = 0.5
#blur = true
startup_mode = "Windowed" # Windowed, Maximized, Fullscreen
title = "Alacritty"
class = { instance = "Alacritty", general = "Alacritty" }
#decorations_theme_variant = "None" # Dark, Light, None

# --- SCROLLING ---
[scrolling]
history = 10000
multiplier = 3

# --- MOUSE ---
[mouse]
hide_when_typing = true

# --- SELECTION ---
[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"
save_to_clipboard = true

# --- KEYBOARD BINDINGS ---
# Syntax: { key = "Key", mods = "Modifier", action = "Action" }
[[keyboard.bindings]]
key = "V"
mods = "Control"
action = "Paste"

[[keyboard.bindings]]
key = "C"
mods = "Control"
action = "Copy"

# --- HINTS (Clickable Links) ---
[[hints.enabled]]
command = "xdg-open" # On macOS use "open"
hyperlinks = true
post_processing = true
persist = false
mouse = { enabled = true, mods = "None" }
binding = { key = "U", mods = "Control|Shift" }
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|ftp:|ftps:|news:|file:|git:|ssh:|itms-services:|test:)[^\\u0000-\\u001F\\u007F-\\u009F<>\"\\s{-}\\^⟨⟩`]+"

# --- ENVIRONMENT VARIABLES ---
[env]
TERM = "alacritty"
